/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const on_Earningfiles_Upload = require('./code/on-earningfiles-upload');

class earning_uploadSrv extends LCAPApplicationService {
    async init() {

        this.on('upload', 'EarningFiles', async (request) => {
            return on_Earningfiles_Upload(request);
        });

        return super.init();
    }
}


module.exports = {
    earning_uploadSrv
};